---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7-slim
params:
  GITHUB_API_TOKEN: ((github-api-token))
  ZENHUB_API_TOKEN: ((zenhub-api-token))
  CONFIG_NAME: ((config-name))
inputs:
  - name: ce-reports
outputs:
  - name: report-output
run:
  path: bash
  args:
    - -exc
    - |
      pip install -r ce-reports/requirements/zenhub-policies.txt
      python ce-reports/reports/zenhub_policies.py > report-output/out.txt
      cat report-output/out.txt
