---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.7-slim
params:
  GITHUB_API_TOKEN: ((github-api-token))
  ZENHUB_API_TOKEN: ((zenhub-api-token))
inputs:
  - name: ce-reports
outputs:
  - name: card-output
run:
  path: bash
  args:
    - -exc
    - |
      pip install -r ce-reports/requirements/card-age-report.txt
      python ce-reports/reports/card_age.py > card-output/out.txt
      cat card-output/out.txt
