---
docker-credentials: &docker-credentials
  username: ((ce-dockerhub-id))
  password: ((ce-dockerhub-token))

resources:
- name: ce-reports
  type: git
  source:
    uri: https://github.com/openstax/ce-reports.git
- name: daily-checkin
  type: time
  source:
    location: America/Chicago
    start: ((start-time))
    stop: ((stop-time))
    days: ((days))
- name: notify-slack
  type: slack
  source:
    url: ((slack-webhook-content-engineering))

resource_types:
  - name: slack
    type: docker-image
    source:
      repository: pumazi/concourse-slack-notification-resource
      <<: *docker-credentials

jobs:
- name: job-list-open-prs
  public: true
  serial: true
  plan:
  - get: daily-checkin
    trigger: true
  - get: ce-reports
  - task: generate-list
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: python
          tag: 3.7-slim
          <<: *docker-credentials

      inputs:
      - name: ce-reports
      outputs:
      - name: open-prs

      run:
        path: /bin/bash
        args: ["-c", "ce-reports/reports/list_open_prs.py | tee open-prs/out"]
      params:
        GITHUB_BEARER_TOKEN: ((github-api-token))
        ORGANIZATIONS: openstax,Rhaptos
        DEVELOPERS: ((developers))
        REVIEWERS: ((reviewers))
        BOTS: ((bots))

    on_success:
      put: notify-slack
      params:
        text_file: open-prs/out
