---
resource_types:

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook-content-engineering))

  - name: daily-checkin
    type: time
    source:
      location: America/Chicago
      start: 08:30
      stop: 09:30
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: ce-reports
    type: git
    source:
      uri: https://github.com/openstax/ce-reports
      branch: check-acceptance-criteria

jobs:
  - name: run-report
    public: true
    plan:
    - get: daily-checkin
      trigger: true
    - get: ce-reports
    - task: generate-report
      file: ce-reports/tasks/run-zenhub-policy-report.yml
      params:
        GITHUB_API_TOKEN: ((github-api-token))
        ZENHUB_API_TOKEN: ((zenhub-api-token))
        CONFIG_NAME: ((config-name))
    on_success:
      put: notify
      params:
        text_file: report-output/out.txt
