---
resources:

  - name: daily-checkin
    type: time
    source:
      location: America/Chicago
      start: 10:30
      stop: 11:00
      days: [Monday, Tuesday, Wednesday, Thursday, Friday]

  - name: ce-reports
    type: git
    source:
      uri: https://github.com/openstax/ce-reports

jobs:
  - name: run-report
    build_log_retention:
      builds: 3
      minimum_succeeded_builds: 1
    public: true
    plan:
    - get: daily-checkin
      trigger: true
    - get: ce-reports
    - task: generate-report
      file: ce-reports/tasks/run-zenhub-policy-report.yml
      params:
        GITHUB_API_TOKEN: ((github-api-token))
        ZENHUB_API_TOKEN: ((zenhub-api-token))
        CONFIG_NAME: ce_zenhub_policies.config.yml
    on_success:
      task: notify slack
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: curlimages/curl
            username: ((ce-dockerhub-id))
            password: ((ce-dockerhub-token))
        inputs:
        - name: report-output
        params:
          WEBHOOK_URL: ((slack-webhook-content-engineering))
        run:
          path: /bin/sh
          args:
          - -cxe
          - |-
            message=$(cat report-output/out.txt)
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" "$WEBHOOK_URL"
